// Problem 2. Maximal sum

// Write a program that reads a rectangular matrix of size N x M and finds in it the square 3 x 3 that has maximal sum of its elements.

using System;
class MaxSubmatrixSum
{
    // printing the entire matrix, separate color for the max sum cells
    private static void PrintMatrix(int[,] matrix, int maxRow, int maxCol)
    {
        for (int rows = 0; rows < matrix.GetLength(0); rows++)
        {
            for (int cols = 0; cols < matrix.GetLength(1); cols++)
            {
                Console.ForegroundColor = ConsoleColor.DarkYellow;
                if (rows >= maxRow && rows <= maxRow + 2 && cols >= maxCol && cols <= maxCol + 2)
                {
                    Console.ForegroundColor = ConsoleColor.Yellow;
                }

                Console.Write("{0,4}", matrix[rows, cols]);
                Console.ForegroundColor = ConsoleColor.DarkYellow;
            }
            Console.WriteLine();
        }
        Console.WriteLine();
    }

    // takes a starting point and calculates the sum in starting cell + 2 cells to the right, starting cell plus 2 cells down
    static int CalcSum(int startRow, int startCol, int[,] matrix)
    {
        int sum = 0;
        for (int row = startRow; row < startRow + 3; row++)
        {
            for (int col = startCol; col < startCol + 3; col++)
            {
                sum = sum + matrix[row, col];
            }
        }

        return sum;
    }

    static void Main()
    {
        int n;
        int m;
        int[,] matrix;

        Console.WriteLine("Autogenerated random array: \n");

        // random values for n and m, in the specified range
            Random rnd = new Random();
            n = rnd.Next(6, 10);
            m = rnd.Next(8, 10);
            matrix = new int[n, m];
            for (int row = 0; row < n; row++)
            {
                for (int col = 0; col < m; col++)
                {
                    // rnd.Next(20) - 10; will be the random matrix cell value
                    // Returns a non-negative random integer that is less than the specified maximum.
                    matrix[row, col] = rnd.Next(20) - 10; // minus 10 so that some of the numbers are negative
                }
            }

        // sum calculation declarations
        int maxSum = int.MinValue;
        int tmpSum = 0;
        int maxRow = 0;
        int maxCol = 0;

        for (int row = 0; row < n - 2; row++)
        {
            for (int col = 0; col < m - 2; col++)
            {
                // calculate sum for every 3 * 3 square
                tmpSum = CalcSum(row, col, matrix);

                // stop if the max sum is reached
                if (tmpSum > maxSum)
                {
                    maxRow = row;
                    maxCol = col;
                    maxSum = tmpSum;
                }
            }
        }

        // print the matrix
        PrintMatrix(matrix, maxRow, maxCol);
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("Maximal sum is {0}", maxSum);
    }
}

