// Problem 6.* Matrix class

/* Write a class Matrix, to hold a matrix of integers. Overload the operators for adding, 
 * subtracting and multiplying of matrices, indexer for accessing the matrix content and ToString().
 */

using System;
using System.Text;

class MatrixUI
{
    static void Main()
    {
        Console.WriteLine("Autogenerated random matrices: \n");

        // random value for n in the specified range
        Random rnd = new Random();
        int n = rnd.Next(2, 4);

        // allocating the matrices
        Matrix matrix1 = new Matrix(n, n);
        Matrix matrix2 = new Matrix(n, n);

        // filling both matrices at the same time
        for (int row = 0; row < n; row++)
        {
            for (int col = 0; col < n; col++)
            {
                // rnd.Next(4) will be the random matrix cell values
                // Returns a non-negative random integer that is less than the specified maximum.
                matrix1[row, col] = rnd.Next(4);
                matrix2[row, col] = rnd.Next(4);
            }
        }

    Console.WriteLine("Print First Matrix, using the ToString() method:\n");
    Console.WriteLine(matrix1.ToString());

    Console.WriteLine("Print Second Matrix, using the ToString() method:\n");
    Console.WriteLine(matrix2.ToString());

    Console.WriteLine("Addition of the Matrices:\n");
    Console.WriteLine(matrix1 + matrix2);

    Console.WriteLine("Subtraction of the Matrices:\n");
    Matrix result = matrix1 - matrix2;

    // print the subtraction result matrix
    for (int row = 0; row < n; row++)
    {
        for (int col = 0; col < n; col++)
        {
            Console.Write("{0,2} ", result[row, col]);
        }
        Console.WriteLine();
    }
    Console.WriteLine();

    Console.WriteLine("Multiplication of the Matrices:\n");
    Console.WriteLine(matrix1 * matrix2);
    }
}
