// This program calculates the maximal row plus column sum in a given matrix

using System;

class MaximalColumnSum
{
    static void Main(string[] args)
    {
        // generate matrix
        int n;
        int m;
        int[,] matrix;

        Console.WriteLine("Autogenerated random matrix: \n");
        Random rnd = new Random();
        n = rnd.Next(4, 6);
        m = rnd.Next(4, 6);
        matrix = new int[n, m];

        // fill the matrix
        for (int row = 0; row < n; row++)
        {
            for (int col = 0; col < m; col++)
            {
                matrix[row, col] = rnd.Next(20);
            }
        }

        // sum calculation declarations
        int maxSum = int.MinValue;
        int tmpSumRow = 0;
        int tmpSumCol = 0;
        int maxCol = 0;
        int maxRow = 0;

        for (int rowIndex = 0; rowIndex < n; rowIndex++)
        {
            for (int colIndex = 0; colIndex < m; colIndex++)
            {
                // calculate sum for every column and row
                tmpSumRow = CalculateSumRow(n, colIndex, matrix);
                tmpSumCol = CalculateSumCol(m, rowIndex, matrix);

                // stop if the max sum is reached
                if (tmpSumRow + tmpSumCol > maxSum)
                {
                    maxCol = colIndex;
                    maxRow = rowIndex;
                    maxSum = tmpSumRow + tmpSumCol;
                }
            }
        }
        

        // print the matrix
        for (int row = 0; row < n; row++)
        {
            for (int col = 0; col < m; col++)
            {
                Console.ForegroundColor = ConsoleColor.DarkYellow;
                if (col == maxCol)
                {
                    Console.ForegroundColor = ConsoleColor.Yellow;
                }
                if (row == maxRow)
                {
                    Console.ForegroundColor = ConsoleColor.Yellow;
                }
                Console.Write("{0,4} ", matrix[row, col]);
                Console.ForegroundColor = ConsoleColor.DarkYellow;
            }
            Console.WriteLine();
        }
        Console.WriteLine();

        Console.ForegroundColor = ConsoleColor.White;

        // print the sum = "max sum column" + "max sum row" - "the duplicate value of the cross-point cell"
        Console.WriteLine("Maximal sum is {0}\n", maxSum - matrix[maxRow, maxCol]);
    }

    // calculates row sums
    private static int CalculateSumRow(int n, int colIndex, int[,] matrix)
    {
        int sum = 0;
        for (int row = 0; row < n; row++)
        {
            sum += matrix[row, colIndex];
        }
        return sum;
    }

    // calculates column sums
    private static int CalculateSumCol(int m, int rowIndex, int[,] matrix)
    {
        int sum = 0;
        for (int col = 0; col < m; col++)
        {
            sum += matrix[rowIndex, col];
        }
        return sum;
    }
}




//MaximalRowPlusColumnSum